spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: dante123
    jpa:
      hibernate:
        ddl-auto: create
        h2:
          console:
            enabled: true

fileUploadFolder: C:\Users\laduc\OneDrive\Desktop\FileRepository
